//! The converter against PotreeConverter, on the same file.
//!
//! This is the test Task C6 exists for. The claim being made is that nothing in
//! this repo needs the Potree toolchain any more, and the only honest way to
//! make it is to convert what PotreeConverter converted and put the two
//! manifests side by side.
//!
//! The oracle is `packages/format-potree/src/__fixtures__/brotli.metadata.json`
//! — PotreeConverter 2.0's own output for `lion_takanawa.copc.laz`, vendored
//! into this repo byte for byte because `demo/data` is gitignored. It is in git
//! and it stays in git: a recording of a foreign tool is exactly the thing that
//! must not be regenerated by the tool it is meant to check.
//!
//! **Byte-for-byte is not the bar, and could not be.** Two converters sampling
//! a cloud choose different representative points for a node, so the payloads
//! differ by construction. What must agree is everything a reader computes
//! against: the quantum, the origin, the cube, the spacing, and the record.
//! Those are compared here exactly.

use std::path::{Path, PathBuf};

use serde_json::Value;
use voxelkloud_io::convert::{convert, ConvertOptions, OutputFormat};

fn repo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("the crate sits two levels under the repo root")
}

fn read_json(path: &Path) -> Value {
    serde_json::from_slice(&std::fs::read(path).expect("readable")).expect("JSON")
}

fn vec3(value: &Value) -> [f64; 3] {
    let a = value.as_array().expect("an array");
    [
        a[0].as_f64().unwrap(),
        a[1].as_f64().unwrap(),
        a[2].as_f64().unwrap(),
    ]
}

/// Attribute name, type, element count and width, in order.
fn attributes(manifest: &Value) -> Vec<(String, String, u64, u64)> {
    manifest["attributes"]
        .as_array()
        .expect("attributes")
        .iter()
        .map(|a| {
            (
                a["name"].as_str().unwrap_or_default().to_string(),
                a["type"].as_str().unwrap_or_default().to_string(),
                a["numElements"].as_u64().unwrap_or(0),
                a["size"].as_u64().unwrap_or(0),
            )
        })
        .collect()
}

#[test]
fn our_potree_output_agrees_with_potreeconverters_on_the_same_file() {
    let source = repo().join("demo/potree/pointclouds/lion_takanawa.copc.laz");
    if !source.exists() {
        eprintln!("skipping: {} is not present", source.display());
        return;
    }
    let oracle = read_json(
        &repo().join("packages/format-potree/src/__fixtures__/brotli.metadata.json"),
    );

    let out = std::env::temp_dir().join(format!("voxelkloud-oracle-potree-{}", std::process::id()));
    std::fs::remove_dir_all(&out).ok();
    let options = ConvertOptions::new(vec![source], out.clone(), OutputFormat::PotreeV2(voxelkloud_io::write::potree::PotreeEncoding::Default));
    convert(&options, &mut |_, _| {}).expect("converts");
    let ours = read_json(&out.join("metadata.json"));

    // The point count, first: everything else is a claim about points that are
    // all there.
    assert_eq!(ours["points"], oracle["points"], "point count");

    // The quantum and the origin. PotreeConverter takes the extent's minimum
    // verbatim as the origin, which is the exact choice — the minimum is itself
    // a point out of the file, so every coordinate differs from it by a whole
    // number of quanta. This converter does the same, and this assertion is
    // what says so.
    assert_eq!(vec3(&ours["scale"]), vec3(&oracle["scale"]), "scale");
    assert_eq!(vec3(&ours["offset"]), vec3(&oracle["offset"]), "offset");

    // The cube, anchored at that minimum rather than centred on the data.
    let ours_box = &ours["boundingBox"];
    let oracle_box = &oracle["boundingBox"];
    for (side, a, b) in [
        ("min", vec3(&ours_box["min"]), vec3(&oracle_box["min"])),
        ("max", vec3(&ours_box["max"]), vec3(&oracle_box["max"])),
    ] {
        for axis in 0..3 {
            assert!(
                (a[axis] - b[axis]).abs() < 1e-9,
                "boundingBox.{side}[{axis}]: {} against {}",
                a[axis],
                b[axis]
            );
        }
    }

    // The spacing is the cube's edge over the grid, and it is the number the
    // LOD scheduler divides by. Agreeing on it means a viewer schedules our
    // cloud exactly as it schedules theirs.
    let a = ours["spacing"].as_f64().unwrap();
    let b = oracle["spacing"].as_f64().unwrap();
    assert!((a - b).abs() < 1e-9, "spacing: {a} against {b}");

    // The record. Same names, same types, same order — including the ones that
    // depend on the source being LAS 1.4 (`classification flags`, an `int16`
    // `scan angle`) and the extra dimension the file's own VLR named.
    assert_eq!(attributes(&ours), attributes(&oracle), "attributes");

    std::fs::remove_dir_all(&out).ok();
}

/// The differences that remain, printed rather than asserted.
///
/// Run with `cargo test -p voxelkloud-io --test oracle -- --nocapture` to see
/// them. They are choices, not defects, and the numbers are worth having in
/// front of you when changing either side.
#[test]
fn report_the_shape_difference_against_potreeconverter() {
    let source = repo().join("demo/potree/pointclouds/lion_takanawa.copc.laz");
    if !source.exists() {
        eprintln!("skipping: {} is not present", source.display());
        return;
    }
    let oracle = read_json(
        &repo().join("packages/format-potree/src/__fixtures__/brotli.metadata.json"),
    );

    let out = std::env::temp_dir().join(format!("voxelkloud-oracle-shape-{}", std::process::id()));
    std::fs::remove_dir_all(&out).ok();
    let options = ConvertOptions::new(vec![source], out.clone(), OutputFormat::PotreeV2(voxelkloud_io::write::potree::PotreeEncoding::Default));
    let report = convert(&options, &mut |_, _| {}).expect("converts");
    let ours = read_json(&out.join("metadata.json"));

    println!("                     ours          PotreeConverter");
    println!(
        "points          {:>10}      {:>10}",
        report.write.points, oracle["points"]
    );
    println!(
        "encoding        {:>10}      {:>10}",
        ours["encoding"].as_str().unwrap_or("?"),
        oracle["encoding"].as_str().unwrap_or("?")
    );
    println!(
        "depth           {:>10}      {:>10}",
        ours["hierarchy"]["depth"], oracle["hierarchy"]["depth"]
    );
    println!(
        "stepSize        {:>10}      {:>10}",
        ours["hierarchy"]["stepSize"], oracle["hierarchy"]["stepSize"]
    );
    println!(
        "firstChunkSize  {:>10}      {:>10}",
        ours["hierarchy"]["firstChunkSize"], oracle["hierarchy"]["firstChunkSize"]
    );
    println!("nodes           {:>10}      {:>10}", report.write.nodes, "—");

    std::fs::remove_dir_all(&out).ok();
}
