// Generate the Homebrew formula for a release.
//
// Written from the release artefacts rather than by hand, because a formula is
// four URLs and four checksums and every one of them is a thing to get wrong
// quietly — a mismatched sha256 fails at `brew install` time, on a user's
// machine, days later.
//
// The formula goes in the tap repository (`voxelkloud/homebrew-tap`), which is
// deliberately not pushed to from here: cross-repository writes need a token
// with a wider scope than a release job should hold. The release attaches the
// file; a human copies it.
//
//   node scripts/homebrew-formula.mjs --version 0.1.0 --dist dist --out dist/voxelkloud.rb

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

function arg(name, fallback) {
  const at = process.argv.indexOf(`--${name}`);
  return at >= 0 ? process.argv[at + 1] : fallback;
}

const version = arg("version");
const dist = arg("dist", "dist");
const out = arg("out", join(dist, "voxelkloud.rb"));
if (!version) {
  console.error("usage: homebrew-formula.mjs --version <x.y.z> [--dist dir] [--out file]");
  process.exit(2);
}

// `shasum -a 256 *` output: "<hash>  <name>".
const sums = new Map(
  readFileSync(join(dist, "SHA256SUMS"), "utf8")
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      const [hash, name] = line.trim().split(/\s+/);
      return [name, hash];
    }),
);

const BASE = `https://github.com/voxelkloud/voxelkloud/releases/download/cli-v${version}`;

function asset(target) {
  const name = `voxelkloud-${version}-${target}.tar.gz`;
  const sha = sums.get(name);
  if (!sha) throw new Error(`${name} is not in SHA256SUMS`);
  return { url: `${BASE}/${name}`, sha };
}

const mac = { arm: asset("aarch64-apple-darwin"), intel: asset("x86_64-apple-darwin") };
const linux = {
  arm: asset("aarch64-unknown-linux-musl"),
  intel: asset("x86_64-unknown-linux-musl"),
};

writeFileSync(
  out,
  `# Generated by scripts/homebrew-formula.mjs. Do not edit by hand.
class Voxelkloud < Formula
  desc "Inspect, diagnose, serve and convert point clouds"
  homepage "https://github.com/voxelkloud/voxelkloud"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${mac.arm.url}"
      sha256 "${mac.arm.sha}"
    end
    on_intel do
      url "${mac.intel.url}"
      sha256 "${mac.intel.sha}"
    end
  end

  on_linux do
    on_arm do
      url "${linux.arm.url}"
      sha256 "${linux.arm.sha}"
    end
    on_intel do
      url "${linux.intel.url}"
      sha256 "${linux.intel.sha}"
    end
  end

  def install
    bin.install "voxelkloud"
  end

  test do
    assert_match "voxelkloud", shell_output("#{bin}/voxelkloud --version")
  end
end
`,
);

console.log(`Wrote ${out}`);
